<h1>Nový pojištěnec</h1>

<form method="POST">
    Jméno
    <input type="text" name="name" placeholder="Jméno" required><br><br>
    Přijmení
    <input type="text" name="surname" placeholder="Přijmení" required><br><br>
    Adresa
    <input type="text" name="address" placeholder="Adresa" required><br><br>
    Město
    <input type="text" name="town" placeholder="Město" required><br><br>
    Věk
    <input type="number" name="age" placeholder="věk" required><br><br>
    Telefonní číslo
    <input type="text" name="phone" placeholder="Telefon" required><br><br>
    Heslo
    <input type="password" name="password" placeholder="Heslo" required><br><br>
    Heslo znovu
    <input type="password" name="passwordAgain" placeholder="Heslo znovu" required><br><br>
    <input type="submit" value="uloz">
</form>
