

<form method="POST">
    ID 
    <input type="number" name="ID" placeholder="ID"required><br><br>
    Jméno
    <input type="text" name="newName" placeholder="Jméno" required><br><br>
    Přijmení
    <input type="text" name="newSurname" placeholder="Přijmení" required><br><br>
    Adresa
    <input type="text" name="newAddress" placeholder="Adresa" required><br><br>
    Město
    <input type="text" name="newTown" placeholder="Město" required><br><br>
    Telefonní číslo
    <input type="text" name="newPhone" placeholder="Telefon" required><br><br>
    <input type="submit" value="Uprav">
</form>